import { ConvexError } from "convex/values";

export const ERROR_CODES = {
  PREVIEW_MODE_DISABLED: "PREVIEW_MODE_DISABLED",
  SESSION_REQUIRED: "SESSION_REQUIRED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  ADMIN_REQUIRED: "ADMIN_REQUIRED",
  CUSTOMER_REQUIRED: "CUSTOMER_REQUIRED",
  CATALOG_NOT_FOUND: "CATALOG_NOT_FOUND",
  CATALOG_NOT_OPEN: "CATALOG_NOT_OPEN",
  CATALOG_CLOSED: "CATALOG_CLOSED",
  ACCESS_CODE_INVALID: "ACCESS_CODE_INVALID",
  ACCESS_CODE_EXPIRED: "ACCESS_CODE_EXPIRED",
  ACCESS_GRANT_REQUIRED: "ACCESS_GRANT_REQUIRED",
  BOOK_VARIANT_UNAVAILABLE: "BOOK_VARIANT_UNAVAILABLE",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_ACCESS_DENIED: "ORDER_ACCESS_DENIED",
  ORDER_LOCKED: "ORDER_LOCKED",
  ORDER_EMPTY: "ORDER_EMPTY",
  DUPLICATE_SLUG: "DUPLICATE_SLUG",
  DUPLICATE_ISBN: "DUPLICATE_ISBN",
  DUPLICATE_VARIANT: "DUPLICATE_VARIANT",
  TEST_CLEANUP_NOT_ALLOWED: "TEST_CLEANUP_NOT_ALLOWED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function fail(code: ErrorCode, message: string = code): never {
  throw new ConvexError({ code, message });
}
